Vagrant.configure("2") do |config|
config.vm.box = "opscode-centos-6.8"
config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.8_chef-provisionerless.box"
config.omnibus.chef_version = :latest
config.vm.network "public_network", ip: "192.168.10.59"

config.vm.provision :chef_client do |chef|
chef.provisioning_path = "/etc/chef"
chef.chef_server_url = "https://api.chef.io/organizations/digits"
chef.validation_key_path = "digits-validator.pem"
chef.validation_client_name = "digits-validator"
chef.node_name = "server1"
end
end
